version: "3.9"

services:
  app:
    build: .
    user: "${APP_USER:-root}"
    environment:
      - APP_NAME=laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=http://localhost
    volumes:
      - .:/var/www
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=api-proyecto-6
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - your_data_volume_name:/var/lib/mysql

volumes:
  your_data_volume_name: {}
